### ISSUE TITLE
lack the res of abc_ic_ab_back_mtrl_am_alpha

### ISSUE THREAD

**Issue by yulongsun007** [Nightonke/LeetCoder2#1]
Error:(57, 84) 错误: 找不到符号
符号:   变量 abc_ic_ab_back_mtrl_am_alpha
位置: 类 drawable

**Comment by Nightonke** [comment]
This file is a png in com.android.support\appcompat-v7\23.1.1\res\drawable-hdpi\abc_ic_ab_back_mtrl_am_alpha.png. Just like follow: (there is a picture below)
![abc_ic_clear_mtrl_alpha](https://cloud.githubusercontent.com/assets/7379793/13455694/ed945f80-e099-11e5-8a47-1b204c07919d.png)
If you can't find the file, just download the picture above to your drawable to solve this issue.

**Comment by purple09** [comment]
我也出现了这个问题，我觉得很有可能是某个依赖包里依赖了23.2的或者23.+的v7
包，导致编译的时候直接使用了最新的v7包，但是23.2版本里缺少了这个图片，大坑啊。
只能把资源文件拷贝到项目中了。

**Comment by Nightonke** [comment]
I'm sorry about that. I will check this ASAP, and thanks for your solution.

**Comment by vipheyue** [comment]
我 新建 了 drawable-v19  并且吧abc_ic_ab_back_material.xml 拷贝进了 drawable 和 drawable-v19 以及 改了  compile 'com.android.support:appcompat-v7:23.2.0' 为 23.0.1 都不行 求解决

**Comment by Nightonke** [comment]
Try to change the code, using your own picture for the unfounded one. I will check it later.

**Comment by vipheyue** [comment]
我刚试了一下 在 Android 22以上版本没有问题  我的真机 Android 19  会报错  ,加QQ 详聊 337681920 何悦

**Comment by Nightonke** [comment]
Sorry, but I don't usually use QQ. But I find this [issue](http://stackoverflow.com/questions/35622438/update-android-support-library-to-23-2-0-cause-error-xmlpullparserexception-bin) in stackoverflow. Maybe it helps.

**Comment by Nightonke** [comment]
@vipheyue Sorry, I'm not free these days. If the problem still there, please let me know and I will fix it ASAP.

**Comment by vipheyue** [comment]
解决了 参照你给的 overflow 加了一行  vectorDrawables.useSupportLibrary = true   把我的 gradle 弄为了         classpath 'com.android.tools.build:gradle:2.0.0-beta6'
 然后完美解决.不过 你因该跟新一下你的 gradle 的版本了

**Comment by Nightonke** [comment]
Nice! Yep, I will update the gradle these days~

**Comment by vipheyue** [comment]
你可以公布你的bomb aped 然后上架到应用市场.在bmob里面的安全设置里面 有一个加证书的 不用担心安全问题 公布 APPID 也没有关系 .后期有人用了,才会收到更多的反馈

**Comment by Nightonke** [comment]
Yep! Good suggestion. I will do that these days. Thanks.

**Comment by purple09** [comment]
compile 'com.android.support:appcompat-v7:23.2.1'
23.2.1的包修复了这个问题

**Comment by Nightonke** [comment]
@purple09 Nice!
